/*
 * @(#) Compiled.java	1.1 03/10/10
 *
 * Copyright (c) 1997-2003 Sun Microsystems, Inc. All Rights Reserved.
 *
 * See the file "LICENSE.txt" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 */
package pnuts.compiler;

/**
 * This interface serves to identify classes which are generated by Compiler.
 */
public interface Compiled {
}
